#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_BADGE_MESSAGE_QUEUE_SIZE 20

#define CONFIG_BADGE_LOCAL_RX_PIN 16
#define CONFIG_BADGE_LOCAL_TX_PIN 17

#define CONFIG_BUTTON_LEFT_PIN 26
#define CONFIG_BUTTON_RIGHT_PIN 25
#define CONFIG_JOYSTICK_PIN 36

#endif
